### ISSUE TITLE
Vault interaction not working for second user

### ISSUE THREAD

**Issue by Sir-Deon** [CanzaApps/Baki-contracts#15] opened 2022-09-07 16:26 UTC
index.ts:261 Uncaught (in promise) Error: cannot estimate gas; transaction may fail or may require manual gas limit [ See: https://links.ethers.org/v5-errors-UNPREDICTABLE_GAS_LIMIT ] (reason="execution reverted", method="estimateGas", transaction={"from":"0x8D28Dc74c0374fBEcDccDb5C51561B2faaEeAe82","to":"0xA5d2f2AE7bd05fF9A66f4e3c8E67Ee785fa43518","data":"0x2f86f2b40000000000000000000000000000000000000000000000000000000000000096000000000000000000000000000000000000000000000000000000000000006400000000000000000000000000000000000000000000000000000000000001aa00000000000000000000000000000000000000000000000000000000000002970000000000000000000000000000000000000000000000000000000000000011","accessList":null}, error={"code":-32603,"message":"Internal JSON-RPC error.","data":

**Comment by Sir-Deon** [comment] 2022-09-07 18:35
Hello @David, Marvelous said it could be a test net issue, could you please test on another testnet?

**Comment by David405** [comment] 2022-09-15 15:14
The issue was caused by an overflow, it has been fixed now

**Closed** 2022-09-15 15:14 UTC
